import flattenedNavigationData from '../../autoGeneratedData/rootTopics.json'
import isExternalLink from '../../src/utils/isExternalLink'

/* eslint-disable @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires */
chai.use(require('chai-string'))

describe('Verify links', () => {
  flattenedNavigationData.forEach(({ label, allItems }) => {
    if (label === 'SDK')
      allItems.forEach(path => {
        if (!path.startsWith('mailto') && !path.startsWith('https://stream.launchdarkly.com')) {
          it(`${label}: ${path}`, () => {
            if (isExternalLink(path)) {
              cy.request(path).then(resp => {
                expect(resp.status).to.eq(200)
              })
            } else {
              cy.visit(path)
              cy.get('main a').each($a => {
                const href = $a.prop('href')
                cy.request(`${href}`).then(resp => {
                  expect(resp.status).to.eq(200)
                })
              })
            }
          })
        }
      })
  })
})
