name: Sync repos from private to public
on: deployment_status
jobs:
  private-public-sync:
    if: ${{ github.event.deployment_status.environment == 'production' && github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    name: Private to public repo sync
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - name: Pull changes from public repo
        id: pull
        run: |
          git config --global user.email "launchdarklyreleasebot@launchdarkly.com"
          git config --global user.name "LaunchDarklyReleaseBot"
          git config --global pull.rebase false
          git remote add public 'https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/LaunchDarkly-Docs.git'
          git fetch public

          if git pull public main --no-edit; then
            git pull && git push
            echo "Successfully merged and pushed public changes to private repo. Will sync private to public now."
            echo "::set-output name=has_conflict::false"
          else
            echo "Conflict detected"
            echo "::set-output name=has_conflict::true"
          fi
      - name: Open PR
        if: steps.pull.outputs.has_conflict == 'true'
        run: |
          git checkout -b sync-conflict-${{ github.sha }}
          git commit -am "Adding all with merge conflicts."
          git push -u origin sync-conflict-${{ github.sha }}
          gh pr create -t "CONFLICT: Resolve public repo sync conflict" -b "Syncing changes from public repo [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}). Please resolve conflicts and **merge without squash**."
          echo "::error::Conflict detected. Please review PR."
          exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: 'https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/ld-docs-private.git'
          source_branch: 'main'
          destination_repo: 'https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/launchdarkly/LaunchDarkly-Docs.git'
          destination_branch: 'main'
