name: Style guide checker
on:
  pull_request:
jobs:
  test-pr-review:
    name: EkLine Reviewer
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'launchdarkly/ld-docs-private' }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/ssm-secrets
        name: 'Get Ekline token'
        with:
          aws_assume_role: ${{ vars.AWS_PROD_ROLE_ARN }}
          ssm_parameter_pairs: '/production/common/services/docs/ekline-token = EKLINE_TOKEN'
#       - uses: ekline-io/ekline-github-action@v5
#         name: Run the style guide checker (Ekline)
#         with:
#           content_dir: ./src/content
#           ek_token: ${{ env.EKLINE_TOKEN }}
#           github_token: ${{ secrets.GH_TOKEN }}
#           reporter: github-pr-review
